[package]
name = "vikingchess"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking", "wayland"] }

[workspace]
resolver = "3"
members = ["engine"]
